
trigger:
- master

variables:
  DOTNET_SDK_VERSION: '2.1.401'

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs:
    version: '$(DOTNET_SDK_VERSION)'

- powershell: ./build.ps1
  displayName: 'Execute Cake PowerShell Bootstrapper'

- task: CopyFiles@2
  displayName: 'Copy generated content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/output'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/outpout
    cleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy deployment content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/deployment'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/deployment
    cleanTargetFolder: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    
steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'Free Trial (8bc354b4-f372-41ce-a6c2-856ab22f5fcf)'
    subscriptionId: '8bc354b4-f372-41ce-a6c2-856ab22f5fcf'
    resourceGroupName: mjtest
    location: 'East US'
    csmFile: '$(System.DefaultWorkingDirectory)/drop/drop/deployment/deploy.json'
    
steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'Free Trial (8bc354b4-f372-41ce-a6c2-856ab22f5fcf)'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: 'az storage blob service-properties update --account-name wyamfrankdemo1 --static-website --index-document index.html'
    
steps:
- task: AzureFileCopy@2
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/drop/drop/outpout'
    azureSubscription: 'Free Trial (8bc354b4-f372-41ce-a6c2-856ab22f5fcf)'
    Destination: AzureBlob
    storage: wyamfrankdemo1
    ContainerName: '$web'
